services:
  app:
    image: pyollamabot
    restart: always
    env_file:
      - .env
    build:
      context: ./
    volumes:
      - ./:/app
    command: python3 /app/bot.py
    # command: tail -f /dev/null
